version: '3.7'

networks:
  ressignifica:
    name: ressignifica
    ipam:
      config:
      - subnet: 14.14.14.0/24

services:
  ressignifica-e2e:
    container_name: ressignifica-e2e
    image: node:13.8.0-alpine3.11
    working_dir: /ws/e2e
    entrypoint: /bin/sh -c '/ws/e2e/entrypoint.sh; tail -f'
    volumes:
    - .:/ws
    env_file:
    - e2e/.env.local
    networks:
      ressignifica:
        ipv4_address: 14.14.14.2

  ressignifica-hub:
    container_name: ressignifica-hub
    image: selenium/hub:3.141.59
    ports:
    - 4444
    networks:
      ressignifica:
        ipv4_address: 14.14.14.3

  ressignifica-chrome:
    container_name: ressignifica-chrome
    image: selenium/node-chrome-debug:3.141.59
    ports:
    - 5901:5900
    env_file:
    - selenium/.env.local
    networks:
      ressignifica:
        ipv4_address: 14.14.14.4

  ressignifica-firefox:
    container_name: ressignifica-firefox
    image: selenium/node-firefox-debug:3.141.59
    ports:
    - 5902:5900
    env_file:
    - selenium/.env.local
    networks:
      ressignifica:
        ipv4_address: 14.14.14.5

  ressignifica-ui:
    container_name: ressignifica-ui
    image: node:13.8.0-alpine3.11
    working_dir: /ws/ui
    entrypoint: /bin/sh -c 'yarn install && yarn start:dev; tail -f'
    volumes:
    - .:/ws
    env_file:
    - ui/.env.local
    ports:
    - 7000:3000
    networks:
      ressignifica:
        ipv4_address: 14.14.14.6

  ressignifica-db:
    container_name: ressignifica-db
    image: postgres:12.2-alpine
    working_dir: /ws/db
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
    - .:/ws
    - ./db/migrations:/docker-entrypoint-initdb.d
    environment:
      PGDATESTYLE: iso, dmy
    env_file:
    - db/.env.local
    ports:
    - 5432
    networks:
      ressignifica:
        ipv4_address: 14.14.14.7

  ressignifica-api:
    container_name: ressignifica-api
    image: node:13.8.0-alpine3.11
    working_dir: /ws/api
    entrypoint: /bin/sh -c 'yarn install && yarn start:w; tail -f'
    volumes:
    - .:/ws
    env_file:
    - api/.env.local
    ports:
    - 4000
    networks:
      ressignifica:
        ipv4_address: 14.14.14.8

  ressignifica-nginx:
    container_name: ressignifica-nginx
    image: nginx:1.17.9-alpine
    volumes:
    - .:/ws
    - ./nginx/html:/usr/share/nginx/html
    env_file:
    - nginx/.env.local
    ports:
    - 80:80
    networks:
      ressignifica:
        ipv4_address: 14.14.14.9

