const RECEPTIONS = [
  { id: 1, name: 'João' },
  { id: 2, name: 'Francisco' },
  { id: 3, name: 'Manoel' }
]
const RECEPTION_TO_ADD = { id: 4, name: 'Raimundo' }
const RECEPTIONS_AFTER_ADD = [ ...RECEPTIONS, RECEPTION_TO_ADD ]
const RECEPTION_TO_REMOVE_INDEX = 1
const RECEPTION_TO_REMOVE = RECEPTIONS[RECEPTION_TO_REMOVE_INDEX]
const RECEPTIONS_AFTER_REMOVE = RECEPTIONS
  .filter((a, i) => i !== RECEPTION_TO_REMOVE_INDEX)
const RECEPTION_TO_CHANGE = { id: 3 }
const RECEPTION_CHANGES = { name: 'José' }
const RECEPTION_AFTER_CHANGE = { ...RECEPTION_TO_CHANGE, ...RECEPTION_CHANGES }

export default {
  RECEPTIONS,
  RECEPTION_TO_ADD,
  RECEPTIONS_AFTER_ADD,
  RECEPTION_TO_REMOVE,
  RECEPTIONS_AFTER_REMOVE,
  RECEPTION_TO_CHANGE,
  RECEPTION_CHANGES,
  RECEPTION_AFTER_CHANGE
}
